### ISSUE TITLE
Discord Group?

### ISSUE THREAD

**Issue by lplaat** [red2211/iPod_ARM_mobo#1]
I came across this project on Reddit and thought it might be a great idea to create a Discord group for discussions around it. Might that be possible?

**Comment by red2211** [comment]
Nice idea, I will create dc group for the project tomorrow maybe.
When created, I will give links to it here on Git and also will post on Reddit in next update.

**Comment by red2211** [comment]
Here is discord channel for this project! https://discord.gg/7t6Rf6DQ
